import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import Sidebar from "@/Components/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Next.js tailwind admin app",
  description: "Generated by Next.js tailwind admin app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body>
        <AppRouterCacheProvider>
          <div className="main flex">
            <div className="sidebarWrapper w-[18%] h-screen">
              <div className="sidebar">
                <Sidebar />
              </div>
            </div>
            <div className="rightContent w-[82%] h-screen">
              {children}
            </div>
          </div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
