import "./globals.css";

export const metadata = {
  title: "Next.js tailwind admin app",
  description: "Generated by Next.js tailwind admin app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className="dark">{children}</body>
    </html>
  );
}
